# -*- coding: utf-8 -*-
"""
/***************************************************************************
 spkbasindelineator
                                 A QGIS plugin
 This plugin will delineate basins for the proposed area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-16
        git sha              : $Format:%H$
        copyright            : (C) 2021 by SPK HydroTech
        email                : spkhydrotech@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.           
    
*  This file is part of SPK Basi Delineator.

*  SPK Basi Delineator is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.

*  SPK Basi Delineator is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.

*  You should have received a copy of the GNU General Public License
*  along with SPK Basi Delineator.  If not, see <https://www.gnu.org/licenses/>.                        *
 *                                                                         *
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load spkbasindelineator class from file spkbasindelineator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SPK_Basin_Delineator import spkbasindelineator
    return spkbasindelineator(iface)
